### ISSUE TITLE
impressum shows error

### ISSUE THREAD

**Issue by deradre** [schdief/moveez#106]
ReferenceError: /usr/src/app/app/views/impressum/index.ejs:1
 >> 1| <% include ../partials/header %>
    2| 
    3| <div class="ui main text container" id="container">
    4|     <div class="ui top attached">

/usr/src/app/app/views/partials/header.ejs:35
    33|                 <hr class="d-sm-none">
    34|                 <a id="logout" href="/logout" class="btn btn-icon-danger btn-danger">
 >> 35|                     <i class="fas fa-sign-out-alt"></i> Logout (<%= username %>)
    36|                 </a>
    37|             </div>
    38|         </nav>

username is not defined
    at eval (eval at compile (/usr/src/app/node_modules/ejs/lib/ejs.js:633:12), <anonymous>:16:26)
    at eval (eval at compile (/usr/src/app/node_modules/ejs/lib/ejs.js:633:12), <anonymous>:38:10)
    at returnedFn (/usr/src/app/node_modules/ejs/lib/ejs.js:668:17)
    at tryHandleCache (/usr/src/app/node_modules/ejs/lib/ejs.js:254:36)
    at View.exports.renderFile [as engine] (/usr/src/app/node_modules/ejs/lib/ejs.js:485:10)
    at View.render (/usr/src/app/node_modules/express/lib/view.js:135:8)
    at tryRender (/usr/src/app/node_modules/express/lib/application.js:640:10)
    at Function.render (/usr/src/app/node_modules/express/lib/application.js:592:3)
    at ServerResponse.render (/usr/src/app/node_modules/express/lib/response.js:1012:7)
    at impressum (/usr/src/app/app/controllers/impressum.js:2:9)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at next (/usr/src/app/node_modules/express/lib/router/route.js:137:13)
    at Route.dispatch (/usr/src/app/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/usr/src/app/node_modules/express/lib/router/layer.js:95:5)
    at /usr/src/app/node_modules/express/lib/router/index.js:281:22
    at Function.process_params (/usr/src/app/node_modules/express/lib/router/index.js:335:12)

**Comment by deradre** [comment]
[ ] rearrange tests
[ ] write new test for impressum page
