### ISSUE TITLE
FacebookTokenError: Error validating client secret

### ISSUE THREAD

**Issue by schdief** [schdief/moveez#73]
FacebookTokenError: Error validating client secret.
    at Strategy.parseErrorResponse (/usr/src/app/node_modules/passport-facebook/lib/strategy.js:198:12)
    at Strategy.OAuth2Strategy._createOAuthError (/usr/src/app/node_modules/passport-oauth2/lib/strategy.js:405:16)
    at /usr/src/app/node_modules/passport-oauth2/lib/strategy.js:175:45
    at /usr/src/app/node_modules/oauth/lib/oauth2.js:191:18
    at passBackControl (/usr/src/app/node_modules/oauth/lib/oauth2.js:132:9)
    at IncomingMessage.<anonymous> (/usr/src/app/node_modules/oauth/lib/oauth2.js:157:7)
    at IncomingMessage.emit (events.js:198:15)
    at endReadableNT (_stream_readable.js:1139:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)

Maybe due to linebreak in env app secret?
KETCHUP_MASTER_PROD_SERVICE_HOST=***
GUI_8_LOGIN_WITH_FACEBOOK_UAT_SERVICE_HOST=***
FACEBOOK_APP_SECRET=***

GUI_MASTER_PROD_PORT_80_TCP_PROTO=***
COY_OTTER_NGINX_INGRESS_CONTROLLER_SERVICE_HOST=***

**Comment by schdief** [comment]
using echo -n when creating the secret helped!

https://github.com/kubernetes/kubernetes/issues/23404#issuecomment-203404986
